[package]
name = "setup_participants"
version = "0.1.0"
edition = "2021"

[lib]
name = "setup_participants"
path = "src/lib.rs"

[dependencies]
utils = { path = "../../utils" }
tokio = { workspace = true }
solana-sdk = { workspace = true }
