[package]
name = "keypair_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-zk-sdk = { workspace = true }
solana-client = { workspace = true }
dotenvy = { workspace = true }
